# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)		+= phy-core.o
obj-$(CONFIG_PHY_LPC18XX_USB_OTG)	+= phy-lpc18xx-usb-otg.o
obj-$(CONFIG_PHY_XGENE)			+= phy-xgene.o
obj-$(CONFIG_PHY_STIH407_USB)		+= phy-stih407-usb.o
obj-$(CONFIG_PHY_STIH41X_USB)		+= phy-stih41x-usb.o
obj-$(CONFIG_PHY_QCOM_QMP)		+= phy-qcom-qmp.o
obj-$(CONFIG_PHY_QCOM_UFS) 	+= phy-qcom-ufs.o
obj-$(CONFIG_PHY_QCOM_UFS) 	+= phy-qcom-ufs-qmp-14nm.o
obj-$(CONFIG_PHY_QCOM_UFS) 	+= phy-qcom-ufs-qmp-v3.o
obj-$(CONFIG_PHY_QCOM_UFS) 	+= phy-qcom-ufs-qrbtc-sdm845.o
obj-$(CONFIG_PHY_QCOM_UFS) 	+= phy-qcom-ufs-qmp-v3-660.o
obj-$(CONFIG_PHY_TUSB1210)		+= phy-tusb1210.o
obj-$(CONFIG_PHY_BRCM_SATA)		+= phy-brcm-sata.o
obj-$(CONFIG_PHY_PISTACHIO_USB)		+= phy-pistachio-usb.o
obj-$(CONFIG_ARCH_SUNXI)		+= allwinner/
obj-$(CONFIG_ARCH_MESON)		+= amlogic/
obj-$(CONFIG_LANTIQ)			+= lantiq/
obj-$(CONFIG_ARCH_MEDIATEK)		+= mediatek/
obj-$(CONFIG_ARCH_RENESAS)		+= renesas/
obj-$(CONFIG_ARCH_ROCKCHIP)		+= rockchip/
obj-$(CONFIG_ARCH_TEGRA)		+= tegra/
obj-y					+= broadcom/	\
					   hisilicon/	\
					   marvell/	\
					   motorola/	\
					   qualcomm/	\
					   ralink/	\
					   samsung/	\
					   st/		\
					   ti/
